#!/usr/bin/env node
// scripts/generate-sitemap.js
// ─────────────────────────────────────────────────────────────────────────────
// Regenerates sitemap.xml from two sources:
//   1. FIXED_ROUTES below — the small set of static pages that never change
//   2. LANDING_PAGES from src/seo/landingPagesConfig.js — every programmatic
//      SEO landing page, so adding a new one there automatically shows up
//      here on the next run. No more hand-editing sitemap.xml when a new
//      landing page ships.
//
// Run manually for now: `node scripts/generate-sitemap.js` from the project
// root, then commit the resulting sitemap.xml. Wiring this into the build
// step (or the "dynamic sitemap serverless function" noted as a TODO in the
// current sitemap.xml's own header comment) is the natural next step once
// package/agent detail pages need to be in here too — this script doesn't
// attempt that yet since it would need a live Supabase query, not just
// static config.
// ─────────────────────────────────────────────────────────────────────────────
import { writeFileSync } from 'node:fs';
import { LANDING_PAGES } from '../src/seo/landingPagesConfig.js';

const SITE_ORIGIN = 'https://www.umrahmarket.net';

const FIXED_ROUTES = [
  { path: '/',            changefreq: 'daily',   priority: '1.0' },
  { path: '/agents',      changefreq: 'daily',   priority: '0.9' },
  { path: '/guidance',    changefreq: 'monthly', priority: '0.7' },
  { path: '/experiences', changefreq: 'monthly', priority: '0.6' },
  { path: '/verified',    changefreq: 'monthly', priority: '0.6' },
];

const landingRoutes = LANDING_PAGES.map((entry) => ({
  path: entry.path,
  changefreq: 'weekly', // package availability under these pages changes more often than the fixed pages above
  priority: '0.8',
}));

const allRoutes = [...FIXED_ROUTES, ...landingRoutes];

const urlEntries = allRoutes.map((r) => `  <url>
    <loc>${SITE_ORIGIN}${r.path}</loc>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Sitemap for umrahmarket.net.
  Generated by scripts/generate-sitemap.js — DO NOT hand-edit the <url>
  entries below directly; add/remove landing pages in
  src/seo/landingPagesConfig.js and re-run this script instead, or your
  edits will be overwritten next run.

  Package pages (/package/:id) and agent pages (/agents/:id) are still
  dynamic and NOT listed here — they change as agents add/update listings.
  Generate those separately from Supabase as a small serverless function
  (same pattern already used for the Open Graph meta tag function) that
  queries active packages/verified agents and outputs <url> entries with
  lastmod from updated_at. Until then, Google discovers those pages by
  crawling links from the homepage, landing pages, and /agents listing.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

writeFileSync(new URL('../sitemap.xml', import.meta.url), xml);
console.log(`sitemap.xml written with ${allRoutes.length} URLs (${FIXED_ROUTES.length} fixed + ${landingRoutes.length} landing pages).`);
